### ISSUE TITLE
Update dialect to account for unsupported features

### ISSUE THREAD

**Issue by binarydud** [binarydud/redshift_sqlalchemy#11]
There are several items inherited from the PGDialect that this dialect needs to override. Let's record them here and then update the dialect:
- [ ] remove enum support
- [ ] remove sequence

**Comment by scribu** [comment]
I'm having trouble with an auto-incrementing column:

``` python
class Article(Base):
    article_id = sa.Column(sa.Integer, primary_key=True)
```

The SQL that SQLAlchemy generates looks like this:

``` sql
CREATE TABLE articles (
  article_id SERIAL NOT NULL
```

but it should look something like this:

``` sql
CREATE TABLE articles (
  article_id int IDENTITY(0, 1)
```

http://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_examples.html

**Comment by graingert** [comment]
@scribu please move this issue to https://github.com/sqlalchemy-redshift/sqlalchemy-redshift
