### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by mjschultz** [binarydud/redshift_sqlalchemy#20]
It looks like master now supports a few new features like:
* putting column encodings as parameters in the table declaration
* allowing sortkey/distkey to be defined in the table declaration
* parallel unloading of statements

According to [PyPI the last release was Jan. 14](https://pypi.python.org/pypi/redshift-sqlalchemy), any chance you can cut a new release?

(Sorry to nag since I think I also requested the Jan 14 release :)

**Comment by kristi** [comment]
+1 would be nice to release this with the updates

**Comment by graingert** [comment]
I've cut a new release called https://pypi.python.org/pypi/sqlalchemy-redshift/
