### ISSUE TITLE
Sequences are disabled for Redshift

### ISSUE THREAD

**Issue by jobevers** [binarydud/redshift_sqlalchemy#24]
When making an integer primary key, sqlalchemy wants to also create a sequence, which are unsupported: http://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-features.html.

**Comment by GabKlein** [comment]
+1

**Comment by graingert** [comment]
This is a duplicate of #9 and fixed in https://pypi.python.org/pypi/sqlalchemy-redshift/0.1.0

**Comment by nwbvt** [comment]
I'm still seeing this on version 0.4
