### ISSUE TITLE
redshift doesn't support check constraints

### ISSUE THREAD

**Issue by adamgreenhall** [binarydud/redshift_sqlalchemy#26]
I'm seeing the redshift dialect produce check constraints on bool columns. But [check constraints are not supported](http://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-features.html). Is there a place where they can be removed?

Example:

    import pandas as pd
    from sqlalchemy.schema import CreateTable
    from sqlalchemy import create_engine
    con = create_engine('redshift+psycopg2://{user}:{password}@{host}:{port}/{database}')
    df = pd.DataFrame(dict(some_bool=[True, False, True], other=[1,2,3]))

    tbl = pd.io.sql.SQLTable(
        name='test_table',
        frame=df,
        pandas_sql_engine=pd.io.sql.SQLDatabase(con),
        )
    print tbl.table
    print str(CreateTable(tbl.table))

Result:

    Table('test_table', MetaData(bind=<pandas.io.sql.SQLDatabase object at 0x103813f50>), Column('index', BigInteger(), table=<test_table>), Column('other', BigInteger(), table=<test_table>), Column('some_bool', Boolean(), table=<test_table>), schema=None)

    CREATE TABLE test_table (
        index BIGINT, 
        other BIGINT, 
        some_bool BOOLEAN, 
        CHECK (some_bool IN (0, 1))
    )

Workaround:

    tbl.table.constraints = set()
    print str(CreateTable(tbl.table))

    CREATE TABLE test_table (
        index BIGINT, 
        other BIGINT, 
        some_bool BOOLEAN
    )

**Comment by aronkyle-lightspeedretail** [comment]
I think you have to explicitly add a check constraint. 
Is it possible that pandas is adding the constraint? Have you tried creating a similar table using sqlalchemy exclusively?

**Comment by adamgreenhall** [comment]
yup - that seems to be the problem. thanks.

**Comment by adamgreenhall** [comment]
actually - I think this is a problem even in pure sqlalchemy tables:

    from sqlalchemy import *
    from sqlalchemy.schema import CreateTable

    con = create_engine('redshift+psycopg2://{user}:{password}@{host}:{port}/{database}')
    tbl = Table('test_table', MetaData(con), Column('other', BigInteger()), Column('some_bool', Boolean()))
    print con.dialect
    print CreateTable(tbl)


outputs:

    <redshift_sqlalchemy.dialect.RedshiftDialect object at 0x103813e90>
    
    CREATE TABLE test_table (
        other BIGINT, 
        some_bool BOOLEAN, 
        CHECK (some_bool IN (0, 1))
    )

**Comment by aronkyle-lightspeedretail** [comment]
Try replacing 
    print CreateTable(tbl)
with 
    print CreateTable(tbl).compile(con)

**Comment by adamgreenhall** [comment]
that works. thanks.
