### ISSUE TITLE
autocommit doesn't work

### ISSUE THREAD

**Issue by whitish** [binarydud/redshift_sqlalchemy#37]
Hi there!

I've added autocommit to my session:

``` python
db = SQLAlchemy(app, session_options={'autocommit': True})
```

But it doesn't work.  I can see changes only after I manually run commit on redshift.

**Comment by graingert** [comment]
Can you post the rest of the code where you send the query?

**Comment by whitish** [comment]
Here is simplified example:

``` python
from models import Campaign
from app import db
camp = Campaign(campid=10,name='camp_name')
db.session.add(camp)
db.session.flush()
```

**Comment by graingert** [comment]
Can you recreate this issue on https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues
